name: Docker GitHub registry

on:
    push:
        paths:
            - 'src/**'
            - 'public/**'
            - 'config/**'
            - 'templates/**'
            - 'Dockerfile'
            - 'docker/**'
            - 'composer.lock'
        branches:
            - master
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Push Docker image to GitHub Container Registry
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: Dockerfile
                    push: true
                    tags: ghcr.io/${{ github.repository }}:latest
                    platforms: linux/amd64
                    cache-from: type=gha,scope=${{ github.workflow }}
                    cache-to: type=gha,scope=${{ github.workflow }},mode=max
